spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://ms-auth
          predicates:
          - Path=/auth/**
        - id: order
          uri: lb://ms-order
          predicates:
          - Path=/order/**
        - id: product
          uri: lb://ms-product
          predicates:
          - Path=/products/**
        - id: delivery
          uri: lb://ms-delivery
          predicates:
          - Path=/delivery/**
server:
  port: 8111
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#logging:
#  level:
#    org.springframework.cloud.gateway: debug