spring:
  flyway:
    locations: classpath:/db/testdata
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_market_delivery?serverTimezone=Europe/Moscow&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect